<! -- START OF /LAYOUT/LAYOUT.PHTML -->
<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/vendor.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.min.css'));
$this->headScript()->prependFile($this->assetUrl('js/default.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/vendor.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));


$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$sitePermissions = $site->sitePermissions();
$userLoggedIn = $this->identity() !== null;

//var_dump(get_class_methods($this->identity()->));
$userName = $userLoggedIn ? $this->identity()->getName() : 'Guest';
$siteUrl = $site->url();
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);

// Add the page slug as a body class in case it’s needed for styling.

if ($nav->findActive($container) && array_key_exists('page-slug',$activePage['page']->getParams())) {
    $this->htmlElement('body')->appendAttribute('class', $activePage['page']->getParams()['page-slug']);
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-N23K88G');</script>
        <!-- End Google Tag Manager -->

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>

    <?php echo $this->htmlElement('body'); ?>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N23K88G" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->

        <div class="full"><?php echo $userBar; ?> </div>
        <header class="full">
            <!--DESKTOP MENU START-->
            <nav class="desktop-nav" aria-label="menu"> 
                <?php echo $this->navigation($this->subNav)->menu()->renderMenu($container, ['maxDepth' =>2]); ?>
                <ul class="nav-icons">
                    <?php if ($userLoggedIn): ?>
                      <li>Hello <strong><?php echo $userName; ?></strong>!</li>
                    <?php endif; ?>
                    <div class="header-search">
                        <?php echo $this->partial('common/search-form',['query' => $this->params()->fromQuery(), 'resourceType' => 'user']); ?>
                    </div>
                    <li><a class="nav-icon nav-search" href="#" title="Search"><img alt='spy glass' src=<?php echo $this->assetUrl('img/svg/icon/search.svg'); ?>></a>
                    </li>
                    <?php if (!$userLoggedIn): ?>
                      <li><a class="nav-icon nav-user-login" href="/login" title="Log-in"><img alt='user login' src=<?php echo $this->assetUrl('img/svg/icon/user-login.svg'); ?>></a></li>
                    <?php endif; ?>
                    <li><a class="nav-icon nav-hamburger" href="#" title="Menu"><img alt='mobile menu' src=<?php echo $this->assetUrl('img/svg/icon/hamburger.svg'); ?>></a></li>
                </ul>
                <!--SUB MENU CONTAINER-->
                <div class="sub-menu-container"></div> 
                <!--MOBILE MENU START-->
                <div class="mobile-menu" aria-label='Mobile Menu'> 
                    <div class="mobile-icons-container"></div>
                    <div class="sub-menu-title">
                        <p>Menu</p>
                    </div>
                    <?php echo $this->navigation($this->subNav)->menu()->renderMenu($container, ['maxDepth' =>2]); ?>
                </div> <!--MOBILE MENU END-->
            </nav> <!--DESKTOP MENU END-->
            <!--MOBILE SEARCH FORM START-->
            <div class="mobile-search">
                <?php echo $this->partial('common/search-form',['query' => $this->params()->fromQuery(), 'resourceType' => 'user']); ?>
            </div> <!--MOBILE SEARCH FORM END-->
        </header>
       
        
        <section id='splash' class='full'></section>
        <section id='primary-content'>
            <a name='main-content'></a>
            <main>
              <div id='content-stack' contentstack>
                <?php echo $this->content; ?>
              </div>
            </main>
        </section>
        <section id='feature-tier-1' class='full'></section>
        <section id='feature-tier-2' class='full'></section>
        <section id='feature-tier-3' class='full'></section>
        <section class='full'>
            <div>
            <div id='secondary-content' style="display:none"></div>
            </div>
        </section>
        <footer class="full">
            <section class="footer-content">
                <div class="sackson-mark">
                    <img alt="the-sid-sackson-portal-mark" src="<?php echo $this->assetUrl('img/png/marks/1x/portal_mark_reversed.png'); ?>">
                </div>
                <div class="vertical"></div>
                <div class="strong-container">
                    <div class="strong-mark">
                        <img alt="strong-museum-mark" src="<?php echo $this->assetUrl('img/png/marks/1x/strong_museum_mark.png'); ?>">
                    </div>
                    <div class="strong-text">
                        <p class="title">The Strong Museum of Play</p>
                        <p>One Manhattan Square<br>
                            Rochester, NY 14607<br>
                            585-263-2700<br>
                            <a href="mailto:info@museumofplay.org">info@museumofplay.org</a>
                        </p>
                    </div>
                </div>
                <div class="vertical"></div>
                <div class="footer-main">
                    <div class="footer--text">  
                        <?php if (!empty($this->themeSetting('footer'))): ?>
                            <?php echo $this->themeSetting('footer') ; ?>
                            <hr class="horizontal">
                        <?php endif; ?>
                    </div>
                    <div class="footer--links">
                        <?php if (!empty($this->themeSetting('footer_links'))): ?>
                            <?php echo $this->themeSetting('footer_links'); ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="vertical mobileline"></div>
                <div class="footer--logo">
                    <img alt="national-archives-mark" src="<?php echo $this->assetUrl('img/png/marks/1x/national_archives_reversed.png'); ?>">
                </div>
            </section>
        </footer>
    </body>
</html>
<! -- END OF /LAYOUT/LAYOUT.PHTML -->
