<?php
$translate = $this->plugin('translate');
$partial = $this->plugin('partial');
?>
<div class="preview-block">
  <?php if ($this->heading): ?>
  <h2><?php echo $this->heading; ?></h2>
  <?php endif; ?>

  <ul class="preview masonry-grid resource-list search-results-list grid">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');
    foreach ($this->resources as $resource):
    ?>
          <?= $partial('agile-item/card', [
            'item' => $resource,
            'containerElement' => 'li',
            'classes' => $this->resourceType
          ]) ?>
    <?php endforeach; ?>
  </ul>

  <?php
  if ($this->linkText):
      /*
      echo $this->hyperlink($this->linkText, $this->url(
          'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
      ));
      */
    ?>

    <div class="browse--collections"><a class="intro-browse--all" href="/s/pathways/browse">Browse all</a> <a class="centre-college" href="/s/pathways/browse?facet%5Bvra%3AplaceOfRepository%5D%5B%5D=Centre+College">Centre College</a> <a class="furman-university" href="/s/pathways/browse?facet%5Bvra%3AplaceOfRepository%5D%5B%5D=Furman+University">Furman University</a> <a class="rollins-college" href="/s/pathways/browse?facet%5Bvra%3AplaceOfRepository%5D%5B%5D=Rollins+College">Rollins College</a> <a class="washington-and-lee" href="/s/pathways/browse?facet%5Bvra%3AplaceOfRepository%5D%5B%5D=W%26L+University">W&amp;L University</a></div>
  <?php
  endif;
  ?>
</div>