<?php
// Variables also available:
// $labelText
// $subtitle
// $buttonText

$partial = $this->plugin('partial');

?>
<!-- HOMEPAGE INTRODUCTION BLOCK TEMPLATE  common/block-layout/homepage-introduction.phtml -->
<div id="block-<?php echo $this->blockId; ?>" class="homepage-introduction slideviewer-container region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">

  <div class="title-area reversed">
      <div>
        <?php if (!empty($labelText)): ?>
            <div class='label'><?php echo $labelText; ?></div>
        <?php endif; ?>
        <?php if (!empty($titleSlideTitle)): ?>
            <h1><?php echo $titleSlideTitle; ?></h1>
        <?php endif; ?>
        <?php if (!empty($subtitle)): ?>
            <div class='subtitle'><?php echo $subtitle; ?></div>
        <?php endif; ?>
        <?php if (!empty($titleSlideIntro)): ?>
            <div class='introductory-text deck'>
              <?php echo $titleSlideIntro; ?>
            </div>
        <?php endif; ?>
          <?php echo $this->partial(
              'common/search-form',
              ['query' => $this->params()->fromQuery(), 'resourceType' => 'user','searchType' => 'browser', 'action' => '/s/pathways/browse']
          ); ?>

          <div id="intro-browse">
              <div class="intro-browse--title">Browse our collections</div>
              <div class="intro-browse--collections"><a class="intro-browse--all" href="browse">All collections</a></div>
          </div>

          <?php if (!empty($buttonText)): ?>
            <a class='slickNext next-slide btn'><?php echo $buttonText; ?></a>
        <?php endif; ?>
      </div>
  </div>
  <?php if($hasAttachments): ?>
    <div class='slide-container'>
      <slide-viewer class="<?php echo $hasAudioAttachment ? 'slideshow-with-audio' : ''; ?>" option-slidesPerRow='<?php echo $optionSlidesPerRow; ?>'  option-autoplay='<?php echo $optionAutoPlay; ?>' option-fade='<?php echo $optionFade; ?>' integratedcontrols>
        <div slot='slides'>
            <?php foreach ($attachments as $attachment): ?>
              <slide-item>
                <?php
                $item = $attachment->item();
                $media = $attachment->media() ?: $item->primaryMedia();
                ?>
                <?= $partial('agile-item/card', [
                  'item' => $item,
                  'containerElement' => 'div',
                  'cardStyle' => 'item-info caption--compact',
                  'heading' => $showTitleOption == 'file_name' && $media ? $media->displayTitle() : $item->displayTitle(),
                  'slot' => 'slide-content'
                ]) ?>
              </slide-item>
            <?php endforeach; ?>
          </div>
          <?php if($hasAudioAttachment): ?>
              <div class="audio-controls">
                  <div class="audio-player">
                      <?php echo $audioAttachment->media()->render(); ?>
                      <div class="audio-message">
                          <a href=='#' class='audio-text-play-control' title='Play audio' data-playbtnmsg='Play audio slideshow' data-stopbtnmsg='Pause audio slideshow'>Play audio slideshow.</a>
                      </div>
                  </div>
                  <?php if ($audioAttachment->caption()): ?>
                      <div class="audio-caption">
                          <?php echo $audioAttachment->caption(); ?>
                      </div>
                  <?php endif; ?>
              </div>
          <?php endif; ?>
      </slide-viewer>
    </div>
  <?php endif;?>
</div>
<!-- END HOMEPAGE INTRODUCTION BLOCK TEMPLATE -->


