<div class="item-with-metadata item-block">
    <?php foreach($attachments as $attachment): ?>
        <div class="item resource">
            <?php $item = $attachment->item(); ?>
            <?php if (empty($item)) continue; ?>
            <div class="resource show">
                <?php if($item->media()): ?>
                    <div class="media-list image-container">
                        <?php
                        foreach ($item->media() as $media):
                            echo $media->linkRaw($this->thumbnail($media, 'large', ['title' => $media->displayTitle()]), null, [
                                'class' => 'media resource'
                            ]);
                        endforeach; ?>
                    </div>
                <?php endif; ?>

                <div class="container-with-tabs-and-panels">
                    <div class="tabs wrapper">
                        <a class="tab description-tab active-tab">description</a>
                        <a class="tab info-tab">info</a>
                    </div>
                    <hr class="wrapper">
                    <div class="panels wrapper">
                        <div class="description-panel">
                            <h3><?php echo $item->link($item->displayTitle()); ?></h3>
                            <?php
                                $caption = $attachment->caption();
                                if ($caption):
                            ?>
                            <div class="caption"><?php echo $caption; ?></div>
                            <?php endif; ?>
                            <?php $values = $item->value('dcterms:description', ['all' => true]); ?>
                            <?php if ($values): ?>
                                <p class="description-text">
                                    <?php foreach ($values as $value) { echo $value->asHtml(); }?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <div class="informations-panel">
                            <?php echo $item->displayValues(); ?>
                        </div>
                        <div class="viewitem-link">
                            <a href="#">view item &gt;</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
