<div id="block-<?php echo $this->blockId; ?>" class="item-list item-list-vertical region <?php echo $this->regionClass; ?> <?php echo $this->classes ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php if ($this->hasTitle): ?>
        <h2><?php echo $this->title; ?></h2>
    <?php endif; ?>
    
        <div class='list-container-vertical'>
        <img alt='' class="list-ornament" src=<?php echo $this->assetUrl('img/png/ornaments/1x/triple-circle-crosshatch.png'); ?>>
        <?php if ($this->hasIntroduction): ?>
            <div class='block-introduction'>
                <?php echo $this->introduction; ?>   
            </div>
        <?php endif; ?>
            
            
    <?php if ($this->hasPages): ?>
        <div class='vertical-page-list'>
            <ul class='tab-ui'>
                <?php foreach($this->pages as $page): ?>
                    <li class='vertical-page-control'>
                        <a class='vertical-item-list-link<?php echo $page['o:active'] ? ' active' : ''; ?>' href='<?php echo $page['o:url']; ?>'><?php echo $page['o:title']; ?></a>

                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    <?php endif; ?>
    </div>
</div>

