<div class="item-showcase item-block">
    <?php foreach ($attachments as $attachment): ?>
        <div class="item resource">
            <?php
                $item = $attachment->item();
                if ($item):
            ?>
            <div class="image-container">
                <?php
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                    endif;
                ?>
            </div>
            <div class="container-with-tabs-and-panels">
                <?php $showTitleOption = $this->showTitleOption; ?>
                <?php if ($showTitleOption == 'item_title'): ?>
                <div class="panels wrapper">
                    <div class="description-panel">
                        <h3><?php echo $item->link($item->displayTitle()); ?></h3>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                        <h3><?php echo $media->displayTitle(); ?></h3>
                        <?php endif; ?>
                        <?php
                            $caption = $attachment->caption();
                            if ($caption):
                        ?>
                        <div class="caption"><?php echo $caption; ?></div>
                        <?php endif; ?>
                        <?php $values = $item->value('dcterms:description', ['all' => true]); ?>
                        <?php if ($values): ?>
                            <p class="description-text">
                                <?php foreach ($values as $value) { echo $value->asHtml(); }?>
                            </p>
                        <?php endif; ?>
                    </div>
                    <div class="viewitem-link">
                        <a href="#">view item</a> &gt;
                    </div>
                </div>
            </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
