<! -- START OF /AGILE-THEME-TOOLS/AGILE-ITEM/BROWSE.PHTML -->
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'browse card-view');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$sortHeadings = [
    [
        'label' => $translate('Sort by Title'),
        'value' => 'dcterms:title'
    ],
    // [
    //     'label' => $translate('Identifier'),
    //     'value' => 'dcterms:identifier'
    // ],
    // [
    //     'label' => $translate('Class'),
    //     'value' => 'resource_class_label'
    // ],
    // [
    //     'label' => $translate('Sort by Date'),
    //     'value' => 'created'
    // ],
];
?>
<div class='browse-tool'>
    <div class="page-header">
        <img alt='' class="page-header-ornament" src=<?php echo $this->assetUrl('img/svg/ornaments/browse-ornament.svg'); ?>>
        <div class="page-header-text-elements">
            <?php if ($itemSetShow): ?>
                <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
                <h3><?php echo $translate('Item set'); ?></h3>
                <div class="metadata">
                    <?php echo $itemSet->displayValues(); ?>
                </div>
                <div class="item-set-items">
                <?php echo '<h3>' . $escape($translate('Browse the Collection')) . '</h3>'; ?>
            <?php else: ?>
                <?php echo $this->pageTitle($translate('Browse the Collection'), 2); ?>
            <?php endif; ?>
            <p class="page-deck">Explore the archives on the Sid Sackson Portal.</p>
            <div class="browse-search-form">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
            <?php echo $this->hyperlink($translate('Advanced Search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
        </div>
    </div>
    
    <?php echo $this->searchFilters(); ?>
    
    <div class="top-bar-ui">
        <h3>Results</h3>
        <div class="browse-controls">
            <div class='sort-selector'>
                <?php echo $this->sortSelector($sortHeadings); ?>
                
            </div>
            <?php echo $this->pagination(); ?>
            <div class="view-options">
                <button class="view-button card-view-btn" type="button" title="Card view" value="card"></button>
                <button class="view-button list-view-btn" type="button" title="List view" value="list"></button>
            </div>
        </div>
    </div>
    
    <div class="mobile-browse-controls">
        <?php echo $this->pagination(); ?>
        <div class="view-options">
            <button class="view-button card-view-btn" type="button" title="Card view" value="card"></button>
            <button class="view-button list-view-btn" type="button" title="List view" value="list"></button>
        </div>
    </div>
    
    <browse-items-container view="card">
        <ul slot="items-container">
        <?php
        $headingTerm = $this->siteSetting('browse_heading_property_term');
        $bodyTerm = $this->siteSetting('browse_body_property_term');
        $viewItemPageTerm = $this->siteSetting('browse_heading_property_term', 'View Item');
        foreach ($items as $item):
            $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
            $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
    
        ?>
            <li class="card">
                <?php 
                    $contentType = [];
                    $contentType['value'] = !empty($item->value('dcterms:type')) ? $item->value('dcterms:type') : 'Item';
                    $viewItemPage = $item->value($viewItemPageTerm, ['default' => $translate('View Item')]);
                ?>
                <p class="item-label"><?php echo($contentType['value']); ?></p>
                <figure class="item-thumbnail">
                    <?php echo $item->linkRaw($this->thumbnail($item, 'large')); ?>
                    <a class="figcaption-link" title='<?php echo $heading; ?>' href='<?php echo $item->url(); ?>'>
                        <figcaption class="item-caption-container"><p><?php echo $escape($body); ?></p></figcaption>
                    </a>
                </figure>
                <div class="item-info">
                    <p class="item-label"><?php echo($contentType['value']); ?></p>
                    <h4 class="item-title"><?php echo $item->link($heading); ?></h4>
                    <?php if ($body): ?>
                    <div class="item-description"><?php echo $escape($body); ?></div>
                    <?php endif; ?>
                    <div class="item-link">
                        <?php echo $item->link($viewItemPage); ?> <span>></span>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    </browse-items-container>
    
    <?php echo ($itemSetShow) ? '</div>' : ''; ?>
    <div class="bottom-bar-ui">
        <?php echo $this->pagination(); ?>
    </div>
</div>
<! -- END OF /AGILE-THEME-TOOLS/AGILE-ITEM/BROWSE.PHTML -->
