<?php
$translate = $this->plugin("translate");
$escape = $this->plugin("escapeHtml");
$this->htmlElement("body")->appendAttribute("class", "item resource show");
$embedMedia = $this->siteSetting("item_media_embed", false);
$itemMedia = $item->media();
?>


<?php $this->trigger("view.show.before"); ?>
<div class='item-container'>
  <div class='item-viewer'>
    <?php if ($this->universalViewer($item)):
      echo $this->universalViewer($item);
    else:
      if ($embedMedia && $itemMedia): ?>
          <div class="media-embeds">
          <?php foreach ($itemMedia as $media):
            echo $media->render();
          endforeach; ?>
          </div>
      <?php endif; ?>
    <?php
    endif; ?>
  </div>
  <div class='item-info item-text'>
    <div class="wayfinding">
      <a href="<?php echo $site->siteUrl(); ?>">Home</a>
      <span>></span>
      <a href="<?php echo $site->siteUrl(); ?>/item">Browse the collection</a>
    </div>
    <header>
      <?php echo $this->pageTitle($item->displayTitle(), 1); ?>
    </header>
    <?php if ($item->value('dcterms:alternative')): ?>
      <div class='subtitle'>
        <?php echo($item->value('dcterms:alternative')); ?>
      </div>
    <?php endif; ?>
    
    <?php
      $descriptionValues = $item->value('dcterms:description', ['all' => true]);
      if ($descriptionValues): ?>
        <div class='description item-text-description'>
          <?php 
            foreach ($descriptionValues as $value):
              printf('<p>%s</p>',$value->asHTML()); 
            endforeach;
          ?>
        </div>
      <?php endif; ?>
    <div class='key-metadata'>
      <div class='metadata-list metadata-list-top'>
        
        <?php
          // Display key terms
          $keyTerms = ['dcterms:creator'=>'Creator','dcterms:date'=>'Date','dcterms:source'=>'Source','dcterms:format'=>'Format'];
          foreach(array_intersect_key($item->values(),$keyTerms) as $term => $value): 
            printf("<div class='property' data-term='%s'>\n",$term);
            printf("   <div class='metadata-label'>%s</div>",!empty($value['alternate_label']) ? $value['alternate_label'] : $keyTerms[$term]);
            print ("    <div class='values'>");
            printf("       <div class='value'>%s</div>",$value['values'][0]);
            print ("    </div>");
            print ("</div>");
          endforeach;
        ?>
        <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <div class="label label-item-info metadata-label"><?php echo $translate(
          "Item sets"
        ); ?></div>
        <?php foreach ($itemSets as $itemSet): ?>
        <div class="value"><a class="item-set-link-top" href="<?php echo $escape(
          $itemSet->url()
        ); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
        <?php endif; ?>
        </div>
      </div> 
    </div>
    <div class='rights'>
      <?php if (!empty($item->value("dcterms:rights"))): ?>
        <div class='rights-statement'>
          <p class="metadata-label">Rights Statement</p>
          <p class="metadata-value"><?php echo($item->value('dcterms:rights')); ?></p>
        </div>
      <?php endif; ?>
      <div class=download-icons>
        <div class='download-item'>
          <?php
            // See https://stackoverflow.com/a/64719808/16534002
            $primary_media = $item->primaryMedia()->originalUrl();
            $url_parts = $primary_media ? explode('/',$primary_media) : '';
            $file_name = array_pop($url_parts);
            $dl_attribute = !empty($file_name) ? ' download="'. $file_name .'"' : '';
            
            $metadata_file_name = "metadata-" . urlencode(strtolower(str_replace(' ','_',$item->title()))) .".json";
          ?>
          <a class='icon-ui' href='<?php echo $item
            ->primaryMedia()
            ->originalUrl(); ?>' <?php echo $dl_attribute; ?>>
              <img alt='thick arrow pointing downward' class='download-img' src='<?php echo $this->assetUrl(
                "img/svg/icon/download.svg"
              ); ?>'>
              <span>Download Item</span>
          </a>
        </div>
        <div class='download-metadata'>
          <a class='icon-ui' target="_blank" type='application/json' href='<?php echo $item->apiUrl(); ?>' download='<?php echo $metadata_file_name; ?>'>
              <img alt='curly brackets' class='download-img' src='<?php echo $this->assetUrl(
                "img/svg/icon/download-metadata.svg"
              ); ?>'>
              <span>Download Metadata</span>
          </a>
        </div>
      </div> 
    </div>

  </div> 
</div>
<div class='item-metadata-block'>
  <header>
    <h2>Full Metadata</h23>
      <img alt='' class="triple-circle-hex" src=<?php echo $this->assetUrl(
        "img/png/ornaments/1x/triple-circle-hex.png"
      ); ?>>
    <div class='subtitle'><?php echo $item->displayTitle(); ?></div>
  </header>
  
  <div class='metadata-list'>
    <?php echo $item->displayValues(); ?>
    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <div class="metadata-label"><?php echo $translate("Item sets"); ?></div>
        <?php foreach ($itemSets as $itemSet): ?>
        <div class="value"><a class="item-set-link" href="<?php echo $escape(
          $itemSet->url()
        ); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
  </div>

<?php
$page = $this->params()->fromQuery("page", 1);
$property = $this->params()->fromQuery("property");
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate("Linked resources"); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
</div>

<div class="transcription-block">
  <img class="transcription-ornament" src="<?php echo $this->assetUrl('img/svg/ornaments/double-hex-text.svg'); ?>" alt="">
  <h2>Transcript</h2>
  <p class="transcript-note"></p>
  <hr>
  <div class="transcription-text">
    <?php if (!empty($item->value("scripto:transcription"))): ?>
        <?php // populated via scriptoSupport.js file ?>
        <div id='transcript-html' data-item-id='<?php echo($item->id()) ?>' data-api-url='<?php echo $item->apiUrl(); ?>'></div>
    <?php else: ?>
        <p class="no-transcription">Transcription not available.</p>
    <?php endif; ?>   
  </div>
  <div class="transcription-link">
    <?php 
      // if (!empty($item->value("scripto:transcription"))) {
      // $transcription = [];
      // $transcription["label"] = !empty(
      //   $itemValue["scripto:transcription"]["alternate_label"]
      // )
      //   ? $itemValue["scripto:transcription"]["alternate_label"]
      //   : "Transcription";
      // $transcription["value"] = $item->value("scripto:transcription");
      // $transcription["uriLabel"] = $item->value("scripto:transcription", [
      //   "type" => "uri",
      // ]);

      // $transcription["link"] = $item->value("scripto:transcription", [
      //   "type" => "uri",
      //   "all" => true
      // ]);

      // foreach ($transcription["link"] as $link) {
      //   echo $link->asHtml();
      // }
      // } 
    ?>
  </div>

</div>
