<?php
$translate = $this->plugin('translate');
$searchType = isset($searchType) && $searchType ?: $this->siteSetting('search_type', 'sitewide');
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
$name = 'fulltext_search';
$action = isset($action) ? $action : '';

switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        // break; // only site search supported
    case 'browser':
        $searchAction = '/s/pathways/browse'; //@todo: get site slug
        $searchValue = $this->escapeHtml($this->params()->fromQuery('q', ''));
        $name='q';
        break;
    case 'sitewide':
    default:
        $searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);
}
?>

<!-- BEGIN SEARCH FORM TEMPLATE  common/search-form.phtml -->
<form action="<?= $action ?>" id="search-form">
    <input type="text" name="<?= $name ?>" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>">
    <button aria-label="<?php echo $translate('Submit search'); ?>" type="submit" tabindex="0"></button>
</form>
<!-- END SEARCH FORM TEMPLATE -->
